### ISSUE TITLE
keyframe animations broken on Safari

### ISSUE THREAD

**Issue by keevkeev** [ampproject/docs#1898]
#### rolling text animation on the home page stacks websites and stories text on Safari

Please provide:

- Page link: https://amp.dev

#### visit amp.dev on Safari

What browser are you using?
- Safari
What O/S are you using?
- iOS, macOs High Sierra

**Comment by keevkeev** [comment]
fixed by #1905

**Comment by matthiasrohmer** [comment]
Sadly not a fix that works consistently 🙁Would be great if you could have another look!

**Comment by matthiasrohmer** [comment]
You might also want to inspect the unoptimized version (https://amp.dev/index.amp.html) vs the unoptimized one (https://amp.dev/) - the first one seems to behave slightly better on Safari. Or at least only breaks every fifth reload instead of almost every one.

**Comment by matthiasrohmer** [comment]
Hmpf ☹️ still broken for me. Reload https://amp-dev-staging.appspot.com several times in Safari.

**Comment by keevkeev** [comment]
@matthiasrohmer which safari version are you using?

**Comment by ithinkihaveacat** [comment]
I can reproduce this too on amp-dev-staging, in both the optimized and non-optimized versions. Latest Safari mobile.

**Comment by matthiasrohmer** [comment]
Thanks @ithinkihaveacat for cross-checking! @keevkeev I am testing with Version 12.1 (14607.1.40.1.4) macOS.

**Comment by keevkeev** [comment]
changing title to 'keyframe animations broken on Safari' as all animations triggered with keyframes are broken sometimes on initial load

**Comment by keevkeev** [comment]
@matthiasrohmer, this issue cannot be replicated in a development environment as all keyframe animations are loading inline, however at build time we are extracting all keyframe animations into a separate style sheet and injecting it at the bottom of the body. My theory is that the content is that all the css and content is being loaded before the keyframe animation stylesheet at build time which causes this issue. All keyframe animations are broken on the page, not just the rolling text in the stage. As I don't have access to deploying to the staging environment I will need someone to else to run a build and test this.
